#!/bin/sh
cd eureka||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t eureka .

cd ../cloud-gateway||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t spring-cloud-gateway .

cd ../webflux||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t webflux .

cd ../webmvc||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t webmvc .

cd ../go||exit
docker build -t go .

cd ../quarkus-vertx||exit
./mvnw clean package
docker build -f Dockerfile.jvm -t quarkus-vertx-jvm .

./mvnw clean package -Pnative # remark if you are build without host GraalVM
docker build -f Dockerfile.native -t quarkus-vertx-native .

cd ..