#!/bin/sh
cd eureka||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t eureka .

cd ../cloud-gateway||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t spring-cloud-gateway .

cd ../webflux||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t webflux .

cd ../webmvc||exit
./mvnw clean install -Dmaven.test.skip=true
docker build -t webmvc .

cd ../go||exit
docker build -t go .

cd ../vertx-rxjava2||exit
./mvnw clean package -Dmaven.test.skip=true
docker build -t vertx-rxjava2 .

cd ../quarkus-vertx-resteasy||exit
./mvnw clean package
docker build -f Dockerfile.jvm -t quarkus-vertx-resteasy-jvm .

./mvnw clean package -Pnative # remark if you are build without host GraalVM
docker build -f Dockerfile.native -t quarkus-vertx-resteasy-native .

cd ../vertx-resteasy-rxjava2||exit
./mvnw clean package -Dmaven.test.skip=true
docker build -t vertx-resteasy-rxjava2 .

cd ..