#!/bin/sh

cd eureka || exit
./build-app
./build-docker

cd ../cloud-gateway || exit
./build-app
./build-docker

cd ../webflux || exit
./build-app
./build-docker

cd ../webmvc || exit
./build-app
./build-docker

cd ../go || exit
./build-docker

cd ../vertx-rxjava2 || exit
./build-app
./build-docker

cd ../quarkus-vertx-resteasy || exit
./build-app
./build-docker
./build-native-app
./build-native-docker

cd ../zuul || exit
./build-app
./build-docker

cd ../vertx-resteasy-rxjava2 || exit
./build-app
./build-docker

cd ../php || exit
./build-docker

cd ..
