version: "3.7"

networks:
  service:
    driver: bridge

services:
  eureka:
    container_name: eureka
    image: eureka
    ports:
      - 8761:8761
    networks:
      - service
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
    deploy:
      resources:
        limits:
          memory: 256m

  spring-cloud-gateway:
    container_name: spring-cloud-gateway
    image: spring-cloud-gateway
    ports:
      - 9090:9090
      - 7001:7001
    networks:
      - service
    #    restart: unless-stopped
    depends_on:
      - eureka
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7001 -Dcom.sun.management.jmxremote.rmi.port=7001
    deploy:
      resources:
        limits:
          memory: 256m

  webflux:
    container_name: webflux
    image: webflux
    ports:
      - 8080:8080
      - 7002:7002
    depends_on:
      - eureka
      - spring-cloud-gateway
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7002 -Dcom.sun.management.jmxremote.rmi.port=7002
    deploy:
      resources:
        limits:
          memory: 256m

  webmvc:
    container_name: webmvc
    image: webmvc
    ports:
      - 8282:8080
      - 7003:7003
    networks:
      - service
    depends_on:
      - eureka
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7003 -Dcom.sun.management.jmxremote.rmi.port=7003
    deploy:
      resources:
        limits:
          memory: 256m

  go:
    container_name: go
    image: go
    ports:
      - 8181:8080
    networks:
      - service
    depends_on:
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m

  quarkus-vertx-resteasy-jvm:
    container_name: quarkus-vertx-resteasy-jvm
    image: quarkus-vertx-resteasy-jvm
    ports:
      - 8383:8080
      - 7004:7004
    networks:
      - service
    depends_on:
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7004 -Dcom.sun.management.jmxremote.rmi.port=7004
    deploy:
      resources:
        limits:
          memory: 256m

  quarkus-vertx-resteasy-native:
    container_name: quarkus-vertx-resteasy-native
    image: quarkus-vertx-resteasy-native
    ports:
      - 8484:8080
    networks:
      - service
    depends_on:
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m

  vertx-rxjava2:
    container_name: vertx-rxjava2
    image: vertx-rxjava2
    ports:
      - 8585:8080
      - 7005:7005
    networks:
      - service
    depends_on:
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7005 -Dcom.sun.management.jmxremote.rmi.port=7005
    deploy:
      resources:
        limits:
          memory: 256m

  vertx-resteasy-rxjava2:
    container_name: vertx-resteasy-rxjava2
    image: vertx-resteasy-rxjava2
    ports:
      - 8686:8080
      - 7006:7006
    networks:
      - service
    depends_on:
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7006 -Dcom.sun.management.jmxremote.rmi.port=7006
    deploy:
      resources:
        limits:
          memory: 256m

  php-5.6-apache2:
    container_name: php-5.6-apache2
    image: php-5.6-apache2
    ports:
      - 8787:80
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m

  php-5.6-nginx:
    container_name: php-5.6-nginx
    image: php-5.6-nginx
    ports:
      - 8788:80
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m

  php-8.0-apache2:
    container_name: php-8.0-apache2
    image: php-8.0-apache2
    ports:
      - 8888:80
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - ./php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
#      - ./php/log/access.log:/var/log/apache2/access.log:rw

  nodejs:
    container_name: nodejs
    image: nodejs
    ports:
      - 8989:8080
    networks:
      - service
    depends_on:
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m

  nginx:
    container_name: nginx
    image: nginx:1.19.6-alpine
    ports:
      - 9191:80
      - 9443:443
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    depends_on:
      - webflux
      - quarkus-vertx-resteasy-jvm
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - ./nginx/route.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/favicon.ico:/usr/share/nginx/html/favicon.ico

  zuul:
    container_name: zuul
    image: zuul
    ports:
      - 9292:9090
      - 7007:7007
    networks:
      - service
    #    restart: unless-stopped
    depends_on:
      - eureka
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7007 -Dcom.sun.management.jmxremote.rmi.port=7007
    deploy:
      resources:
        limits:
          memory: 256m