version: "3.7"

services:
  eureka:
    container_name: eureka
    image: eureka
    ports:
      - 8761:8761
    networks:
      - service
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
    deploy:
      resources:
        limits:
          memory: 256m

  spring-cloud-gateway:
    container_name: spring-cloud-gateway
    image: spring-cloud-gateway
    ports:
      - 9090:9090
      - 7001:7001
    networks:
      - service
    #    restart: unless-stopped
    depends_on:
      - eureka
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7001 -Dcom.sun.management.jmxremote.rmi.port=7001
    deploy:
      resources:
        limits:
          memory: 256m

  webflux:
    container_name: webflux
    image: webflux
    ports:
      - 8080:8080
      - 7002:7002
    depends_on:
      - eureka
      - spring-cloud-gateway
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7002 -Dcom.sun.management.jmxremote.rmi.port=7002
    deploy:
      resources:
        limits:
          memory: 256m

  webmvc:
    container_name: webmvc
    image: webmvc
    ports:
      - 8282:8080
      - 7003:7003
    networks:
      - service
    depends_on:
      - eureka
      - spring-cloud-gateway
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    environment:
      JVM_OPT: |-
        -XX:+UseG1GC
        -XX:MaxRAMPercentage=90.0
        -Xlog:gc:GC.log -XX:+UseStringDeduplication
        -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
        -Dcom.sun.management.jmxremote.port=7003 -Dcom.sun.management.jmxremote.rmi.port=7003
    deploy:
      resources:
        limits:
          memory: 256m

  go:
    container_name: go
    image: go
    ports:
      - 8181:8080
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    deploy:
      resources:
        limits:
          memory: 256m

  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    ports:
      - 9191:80
      - 9443:443
    networks:
      - service
    ulimits:
      nproc: 514933
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: 1025 65000
    depends_on:
      - webflux
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - ./nginx/route.conf:/etc/nginx/nginx.conf:ro

networks:
  service:
    driver: bridge