spring:
  application:
    name: webflux
server:
  port: 8080
eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    webclient:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1