spring:
  application:
    name: webflux
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1