server:
  port: 9090
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: hello-webflux-lb
          uri: lb://webflux
          predicates:
            - Path=/webflux-lb/**
          filters:
            - RewritePath=/webflux-lb/(?<rewrite>.*), /${rewrite}
        - id: hello-webflux
          uri: http://webflux:8080
          predicates:
            - Path=/webflux/**
          filters:
            - RewritePath=/webflux/(?<rewrite>.*), /${rewrite}
        - id: hello-webmvc
          uri: http://webmvc:8080
          predicates:
            - Path=/webmvc/**
          filters:
            - RewritePath=/webmvc/(?<rewrite>.*), /${rewrite}
        - id: hello-go
          uri: http://go:8080
          predicates:
            - Path=/go/**
          filters:
            - RewritePath=/go/(?<rewrite>.*), /${rewrite}
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 2